export const REGISTER_USER = "REGISTER_USER";
export const VERIFIED_USER = "VERIFIED_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const GET_COMPANIES = "GET_COMPANIES"
export const GET_OFFER = "GET_OFFER"
export const GET_OFFER_BY_CATEGORY = "GET_OFFER_BY_CATEGORY"
export const GET_OFFER_BY_ID = "GET_OFFER_BY_ID"
export const GET_SUBCAT_ALL_COMPANY = "GET_SUBCAT_ALL_COMPANY"
